ocr init
openfoodfacts/off-category-classification pull request #75
Opened 2022-06-01 19:50 UTC by AnisZakari

Ocr functions

2022-06-22 10:16 UTC, streino requested changes

2022-06-22 10:16 UTC, streino commented on make_ocr_features/make_OCR_df_and_preprocess.ipynb
> +    "txt_annotations_path = \"INPUT_datasets/txtannotations.jsonl.gzip\"\n",
Where does that file come from? -> add to README
(I couldn't run notebook further, will do when I have the file)

2022-06-22 14:45 UTC, streino commented
Forgot to mention in my review: how is this going to be added to model training?

My suggestion would be to integrate it in the [tdfs dataset generation](https://github.com/openfoodfacts/off-category-classification/blob/master/datasets/off_categories/off_categories.py) and make it available as a (or several) new feature(s).

In any case, the processed OCR data should be output in some way that's easy to process further (and can be released along with other data files?). So pickle probably isn't the best format.

It'd probably also be a good idea to keep line-level correspondence with original data files as well, so we don't have to do costly merge operations on codes if we want to join various feature files. This would pretty much be mandatory if we go the tdfs dataset route.

2022-07-11 21:27 UTC, streino reviewed
I added a few new misc comments, and there are a few from my previous review that you didn't close/comment (esp. https://github.com/openfoodfacts/off-category-classification/pull/75#issuecomment-1163199133), but overall looks good to me.

I won't be able to review in the next 7-10 days, so if you need more feedback maybe @alexgarel can help?

2022-07-11 21:27 UTC, streino commented on make_ocr_features/make_OCR_df_and_preprocess.ipynb
> +    "big_words_dict = defaultdict(str)\n",
I'd move those vars in the next cell so they get properly reinitialized if next cell get re-run.

2022-07-11 21:27 UTC, streino commented on make_ocr_features/utils/OCR_preprocessing.py
> +    text_cleaned = re.sub(r'''(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,
That's quite a regex! Is this something you borrowed (link to source?) or you built? I'll trust you on that one, it looks scary...

2022-07-11 21:27 UTC, streino commented on make_ocr_features/utils/OCR_preprocessing.py
> +    D = {word.lower(): word  for word in str(text).split()}
Pep8: Avoid uppercase vars

2022-07-11 21:27 UTC, streino commented on make_ocr_features/utils/OCR_word_selection.py
> +            w_lower = str(word).lower()
Nitpick: I mentioned it in another comment as well: Why the `str()` call here (and other places)? Aren't we guaranteed that `text.split()` returns strings?

2022-07-11 21:27 UTC, streino commented on make_ocr_features/utils/OCR_word_selection.py
> +    keys: list, default = None
Missing param doc for `word_count_limit`

2022-07-11 21:27 UTC, streino commented on make_ocr_features/utils/OCR_word_selection.py
> +    N_words_to_pick: int, default = 120
Lowercase param (to match function header)

2022-07-11 21:27 UTC, streino commented on make_ocr_features/utils/OCR_preprocessing.py
> +    dont_take = ["kj", "kcal", "kj", "total", "free", "net", "ingredients", "ingredient", "et", "de", "fat", "mg", "cg", "g", "kg", "ml", "cl", "l", "kl", "per", "pour", "valeur", "or", "le", "la", "
`dont_take` is also defined in OCR_word_selection.py. Can it be refactored into a single definition?

2022-07-11 21:27 UTC, streino commented on make_ocr_features/utils/OCR_word_selection.py
> +def get_intersect_words_ocr(sub_ocr_text_dict, N_max = 30):
Pep8: lowercase params

2022-11-21 13:29 UTC, raphael0202 approved these changes
Merging this branch, as all changes are in a distinct directory. We can perform some fixes/updates later.

2022-11-21 13:30 UTC, merged